### ISSUE TITLE
allow switchage to existing scheme when current scheme is gone

### ISSUE THREAD

**Issue by fletcherm** [karlin/working-directory#5]
The scheme listed in currentscheme is missing. I cannot switch to an existing scheme (which does exist in the wd dir) because of this error message: "Your current wdscheme (/Users/fletcher/git/github/working-directory/wd/git-deply.scheme) is missing.
Please fix it."

IMO the switch-to-existing-scheme operation should work even if the currentscheme is busted.

PS
I put myself into this state by accidentally the file listed in currentscheme.

**Comment by karlin** [comment]
In v3.1, this situation should result in switching to the `default` scheme or creating it if that's the one that was missing.
